### PR TITLE
Fixs herberlink (setup_module)

### PR DESCRIPTION
**Pull request by ydFu**
Setup_module Link failure. thx

### CODE REVIEW

**Comment by chusiang** [comment]
Thanks, I have a lot of url need to fix from http://docs.ansible.com/ansible/xxx_module.html to https://docs.ansible.com/ansible/latest/modules/ . 😓

**Comment by ydFu** [comment]
Maybe ,Can find the global var to markdown?<I'm not sure.HAHA>

**Comment by chusiang** [comment]
I will use the `sed` to replace all, thanks. 😁

**Comment by chusiang** [comment]
I have updated some urls of `http://docs.ansible.com/xxx`.

> https://github.com/chusiang/automate-with-ansible/commit/6d8d80b96af9a93ea9b2f9c92d7ef45062442d93

Good night. 💪

**Pull request merged**
